# Generated by Django 5.1.1 on 2024-09-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='other_profile_field_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_profile_field_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
